/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canteen_java;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abc
 */
public class deletefood extends javax.swing.JFrame {

    /**
     * Creates new form deletefood
     */
    
    ADMINF adm=new ADMINF();
    public deletefood() {
        initComponents();
        this.setLocationRelativeTo(null);
        
         adm.fillAddTable(jTable1);
        
         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black);
        jLabel2_del_min.setBorder(label_border);
        jLabel1_del_close.setBorder(label_border);
        
          Border glob_panel_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black);
        jPanel1.setBorder(glob_panel_border);
        jPanel2.setBorder(glob_panel_border);
        jPanel3.setBorder(glob_panel_border);
        
         Border field_border = BorderFactory.createMatteBorder(1,2,1,1,Color.white);
        jTextField1_FOOD_NAME.setBorder(field_border);
        jTextField2_FOOD_TYPE.setBorder(field_border);
        jTextField3_PRICE.setBorder(field_border);
         jTextField1_ID.setBorder(field_border);
        
       
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1_add = new javax.swing.JButton();
        jButton2_del = new javax.swing.JButton();
        jButton3_mod = new javax.swing.JButton();
        jButton4_rec = new javax.swing.JButton();
        jLabel1_del_close = new javax.swing.JLabel();
        jLabel2_del_min = new javax.swing.JLabel();
        jButton5_ord = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1_FOOD_NAME = new javax.swing.JTextField();
        jTextField2_FOOD_TYPE = new javax.swing.JTextField();
        jTextField3_PRICE = new javax.swing.JTextField();
        jButton6_delete = new javax.swing.JButton();
        jButton7_remove = new javax.swing.JButton();
        jLabel4_back = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1_ID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 150, 136));

        jButton1_add.setBackground(new java.awt.Color(51, 51, 51));
        jButton1_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_add.setText("ADD FOOD");
        jButton1_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1_addMouseExited(evt);
            }
        });

        jButton2_del.setBackground(new java.awt.Color(51, 51, 51));
        jButton2_del.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2_del.setForeground(new java.awt.Color(255, 255, 255));
        jButton2_del.setText("DELETE FOOD");
        jButton2_del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2_delMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2_delMouseExited(evt);
            }
        });

        jButton3_mod.setBackground(new java.awt.Color(51, 51, 51));
        jButton3_mod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3_mod.setForeground(new java.awt.Color(255, 255, 255));
        jButton3_mod.setText("MODIFY");
        jButton3_mod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3_mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3_modMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3_modMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3_modMouseExited(evt);
            }
        });

        jButton4_rec.setBackground(new java.awt.Color(51, 51, 51));
        jButton4_rec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4_rec.setForeground(new java.awt.Color(255, 255, 255));
        jButton4_rec.setText("RECORDS");
        jButton4_rec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4_rec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4_recMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4_recMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4_recMouseExited(evt);
            }
        });
        jButton4_rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_recActionPerformed(evt);
            }
        });

        jLabel1_del_close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1_del_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_del_close.setText("x");
        jLabel1_del_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_del_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_del_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1_del_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1_del_closeMouseExited(evt);
            }
        });

        jLabel2_del_min.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2_del_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_del_min.setText("-");
        jLabel2_del_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2_del_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2_del_minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2_del_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2_del_minMouseExited(evt);
            }
        });

        jButton5_ord.setBackground(new java.awt.Color(51, 51, 51));
        jButton5_ord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5_ord.setForeground(new java.awt.Color(255, 255, 255));
        jButton5_ord.setText("ORDERS");
        jButton5_ord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5_ord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5_ordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5_ordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5_ordMouseExited(evt);
            }
        });
        jButton5_ord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_ordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1_add, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2_del, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5_ord, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4_rec, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(jLabel2_del_min, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1_del_close, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4_rec, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton3_mod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5_ord, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel1_del_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2_del_min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2_del, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1280, 50);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FOOD NAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FOOD TYPE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PRICE");

        jTextField1_FOOD_NAME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jTextField2_FOOD_TYPE.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField2_FOOD_TYPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_FOOD_TYPEActionPerformed(evt);
            }
        });

        jTextField3_PRICE.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jButton6_delete.setBackground(new java.awt.Color(0, 84, 140));
        jButton6_delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6_delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton6_delete.setText("DELETE");
        jButton6_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6_deleteMouseExited(evt);
            }
        });
        jButton6_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6_deleteActionPerformed(evt);
            }
        });

        jButton7_remove.setBackground(new java.awt.Color(0, 84, 140));
        jButton7_remove.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7_remove.setForeground(new java.awt.Color(255, 255, 255));
        jButton7_remove.setText("REMOVE FIELDS");
        jButton7_remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7_remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7_removeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7_removeMouseExited(evt);
            }
        });
        jButton7_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7_removeActionPerformed(evt);
            }
        });

        jLabel4_back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4_back.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4_back.setText("<<back");
        jLabel4_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4_backMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ID");

        jTextField1_ID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 6, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2_FOOD_TYPE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jTextField3_PRICE, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(205, 205, 205))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1_ID))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1_FOOD_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton6_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButton7_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4_back, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_FOOD_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2_FOOD_TYPE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4_back, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3_PRICE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 520, 1280, 280);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FOOD NAME", "FOOD TYPE", "PRICE"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 1280, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4_recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_recActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4_recActionPerformed

    private void jLabel2_del_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_del_minMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2_del_minMouseClicked

    private void jLabel2_del_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_del_minMouseEntered
        // TODO add your handling code here:
         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white);
        jLabel2_del_min.setBorder(label_border);
        jLabel2_del_min.setForeground(Color.white);
    }//GEN-LAST:event_jLabel2_del_minMouseEntered

    private void jLabel2_del_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_del_minMouseExited
        // TODO add your handling code here:
         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black);
        jLabel2_del_min.setBorder(label_border);
        jLabel2_del_min.setForeground(Color.black);
    }//GEN-LAST:event_jLabel2_del_minMouseExited

    private void jLabel1_del_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_del_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1_del_closeMouseClicked

    private void jLabel1_del_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_del_closeMouseEntered
        // TODO add your handling code here:
         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white);
        jLabel1_del_close.setBorder(label_border);
        jLabel1_del_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel1_del_closeMouseEntered

    private void jLabel1_del_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_del_closeMouseExited
        // TODO add your handling code here:
         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black);
        jLabel1_del_close.setBorder(label_border);
        jLabel1_del_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel1_del_closeMouseExited

    private void jButton1_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_addMouseEntered
        // TODO add your handling code here:
        jButton1_add.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton1_addMouseEntered

    private void jButton1_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_addMouseExited
        // TODO add your handling code here:
        jButton1_add.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton1_addMouseExited

    private void jButton2_delMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_delMouseEntered
        // TODO add your handling code here:
        jButton2_del.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton2_delMouseEntered

    private void jButton2_delMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_delMouseExited
        // TODO add your handling code here:
        jButton2_del.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton2_delMouseExited

    private void jButton3_modMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_modMouseEntered
        // TODO add your handling code here:
        jButton3_mod.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton3_modMouseEntered

    private void jButton3_modMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_modMouseExited
        // TODO add your handling code here:
        jButton3_mod.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton3_modMouseExited

    private void jButton4_recMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_recMouseEntered
        // TODO add your handling code here:
        jButton4_rec.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton4_recMouseEntered

    private void jButton4_recMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_recMouseExited
        // TODO add your handling code here:
        jButton4_rec.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton4_recMouseExited

    private void jButton1_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_addMouseClicked
        // TODO add your handling code here:
         addfood af=new addfood();
        this.setVisible(false);
        af.setVisible(true);
    }//GEN-LAST:event_jButton1_addMouseClicked

    private void jButton5_ordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_ordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5_ordActionPerformed

    private void jTextField2_FOOD_TYPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_FOOD_TYPEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_FOOD_TYPEActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int rIndex=jTable1.getSelectedRow();
         jTextField1_ID.setText(model.getValueAt(rIndex, 0).toString());
        jTextField1_FOOD_NAME.setText(model.getValueAt(rIndex, 1).toString());
        jTextField2_FOOD_TYPE.setText(model.getValueAt(rIndex, 2).toString());
        jTextField3_PRICE.setText(model.getValueAt(rIndex, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6_deleteMouseEntered
        // TODO add your handling code here:
        jButton6_delete.setBackground(new Color(0,101,183));
    }//GEN-LAST:event_jButton6_deleteMouseEntered

    private void jButton6_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6_deleteMouseExited
        // TODO add your handling code here:
        jButton6_delete.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_jButton6_deleteMouseExited

    private void jButton7_removeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7_removeMouseEntered
        // TODO add your handling code here:
        jButton7_remove.setBackground(new Color(0,101,183));
    }//GEN-LAST:event_jButton7_removeMouseEntered

    private void jButton7_removeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7_removeMouseExited
        // TODO add your handling code here:
        jButton7_remove.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_jButton7_removeMouseExited

    private void jLabel4_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4_backMouseEntered
        // TODO add your handling code here:
        jLabel4_back.setForeground(Color.white);
    }//GEN-LAST:event_jLabel4_backMouseEntered

    private void jLabel4_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4_backMouseExited
        // TODO add your handling code here:
        jLabel4_back.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jLabel4_backMouseExited

    private void jLabel4_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4_backMouseClicked
        // TODO add your handling code here:
         admin ad=new admin();
        this.setVisible(false);
        ad.setVisible(true);

    }//GEN-LAST:event_jLabel4_backMouseClicked

    private void jButton7_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7_removeActionPerformed
        // TODO add your handling code here:
        jTextField1_FOOD_NAME.setText("");
        jTextField2_FOOD_TYPE.setText("");
        jTextField3_PRICE.setText("");
         jTextField1_ID.setText("");
    }//GEN-LAST:event_jButton7_removeActionPerformed

    private void jButton6_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6_deleteActionPerformed
        // TODO add your handling code here:
        try{
               int id=Integer.valueOf(jTextField1_ID.getText());
                if(adm.delete(id))
        {
           JOptionPane.showMessageDialog(rootPane,"FOOD ITEM DELETED SUCCESSFULLY","DELETE FOOD FOOD",JOptionPane.INFORMATION_MESSAGE);
        }else
        {
           JOptionPane.showMessageDialog(rootPane," FOOD ITEM NOT DELETED ","DELETE FOOD",JOptionPane.ERROR_MESSAGE);

        }
           }
           catch(NumberFormatException ex)
           {
               JOptionPane.showMessageDialog(rootPane,ex.getMessage() + "Enter ID","ID ERROR",JOptionPane.WARNING_MESSAGE);
           }
        
         jTable1.setModel(new DefaultTableModel(null,new Object[]{"ID","FOOD NAME","FOOD TYPE","PRICE"}));
        adm.fillAddTable(jTable1);
    }//GEN-LAST:event_jButton6_deleteActionPerformed

    private void jButton3_modMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_modMouseClicked
        // TODO add your handling code here:
        modify mod=new modify();
        this.setVisible(false);
        mod.setVisible(true);
    }//GEN-LAST:event_jButton3_modMouseClicked

    private void jButton5_ordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5_ordMouseClicked
        // TODO add your handling code here:
        orders ord=new orders();
        this.setVisible(false);
        ord.setVisible(true);
    }//GEN-LAST:event_jButton5_ordMouseClicked

    private void jButton5_ordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5_ordMouseEntered
        // TODO add your handling code here:
        jButton5_ord.setBackground(new Color(102,102,102));

    }//GEN-LAST:event_jButton5_ordMouseEntered

    private void jButton5_ordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5_ordMouseExited
        // TODO add your handling code here:
        jButton5_ord.setBackground(new Color(51,51,51));

    }//GEN-LAST:event_jButton5_ordMouseExited

    private void jButton4_recMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_recMouseClicked
        // TODO add your handling code here:
        record rec=new record();
        this.setVisible(false);
        rec.setVisible(true);
    }//GEN-LAST:event_jButton4_recMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deletefood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deletefood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deletefood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deletefood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deletefood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_add;
    private javax.swing.JButton jButton2_del;
    private javax.swing.JButton jButton3_mod;
    private javax.swing.JButton jButton4_rec;
    private javax.swing.JButton jButton5_ord;
    private javax.swing.JButton jButton6_delete;
    private javax.swing.JButton jButton7_remove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_del_close;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_del_min;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4_back;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_FOOD_NAME;
    private javax.swing.JTextField jTextField1_ID;
    private javax.swing.JTextField jTextField2_FOOD_TYPE;
    private javax.swing.JTextField jTextField3_PRICE;
    // End of variables declaration//GEN-END:variables
}
