/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canteen_java;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import com.email.durgesh.Email;
import javax.swing.JTable;
/**
 *
 * @author abc
 */
public class orders extends javax.swing.JFrame {

    /**
     * Creates new form orders
     */
    USERF usr=new USERF();
    public orders() {
        initComponents();
        this.setLocationRelativeTo(null);
        usr.fillorderTable(jTable1);
        
        
         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black);
        jLabel2_ord_close.setBorder(label_border);
        jLabel2_ord_min.setBorder(label_border);
        
          Border glob_panel_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black);
        jPanel1.setBorder(glob_panel_border);
        jPanel2.setBorder(glob_panel_border);
        jPanel3.setBorder(glob_panel_border);
        
        Border field_border = BorderFactory.createMatteBorder(1,2,1,1,Color.white);
        jTextField1_food_name.setBorder(field_border);
        jTextField2_quan.setBorder(field_border);
        jTextField3_totalpri.setBorder(field_border);
         jTextField4_rollno.setBorder(field_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1_add = new javax.swing.JButton();
        jButton2_del = new javax.swing.JButton();
        jButton3_modify = new javax.swing.JButton();
        jButton4_orders = new javax.swing.JButton();
        jButton5_rec = new javax.swing.JButton();
        jLabel2_ord_close = new javax.swing.JLabel();
        jLabel2_ord_min = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_food_name = new javax.swing.JTextField();
        jTextField2_quan = new javax.swing.JTextField();
        jTextField3_totalpri = new javax.swing.JTextField();
        jButton6_done = new javax.swing.JButton();
        jLabel5_back = new javax.swing.JLabel();
        jButton7_cancel = new javax.swing.JButton();
        jTextField4_rollno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 150, 136));

        jButton1_add.setBackground(new java.awt.Color(51, 51, 51));
        jButton1_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_add.setText("ADD FOOD");
        jButton1_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1_addMouseExited(evt);
            }
        });

        jButton2_del.setBackground(new java.awt.Color(51, 51, 51));
        jButton2_del.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2_del.setForeground(new java.awt.Color(255, 255, 255));
        jButton2_del.setText("DELETE FOOD");
        jButton2_del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_delMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2_delMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2_delMouseExited(evt);
            }
        });

        jButton3_modify.setBackground(new java.awt.Color(51, 51, 51));
        jButton3_modify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3_modify.setForeground(new java.awt.Color(255, 255, 255));
        jButton3_modify.setText("MODIFY");
        jButton3_modify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3_modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3_modifyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3_modifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3_modifyMouseExited(evt);
            }
        });

        jButton4_orders.setBackground(new java.awt.Color(51, 51, 51));
        jButton4_orders.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4_orders.setForeground(new java.awt.Color(255, 255, 255));
        jButton4_orders.setText("ORDERS");
        jButton4_orders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4_ordersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4_ordersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4_ordersMouseExited(evt);
            }
        });

        jButton5_rec.setBackground(new java.awt.Color(51, 51, 51));
        jButton5_rec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5_rec.setForeground(new java.awt.Color(255, 255, 255));
        jButton5_rec.setText("RECORDS");
        jButton5_rec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5_rec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5_recMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5_recMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5_recMouseExited(evt);
            }
        });

        jLabel2_ord_close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2_ord_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_ord_close.setText("x");
        jLabel2_ord_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2_ord_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2_ord_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2_ord_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2_ord_closeMouseExited(evt);
            }
        });

        jLabel2_ord_min.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2_ord_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_ord_min.setText("-");
        jLabel2_ord_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2_ord_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2_ord_minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2_ord_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2_ord_minMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1_add, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2_del, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5_rec, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(jLabel2_ord_min, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2_ord_close, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2_ord_close, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1_add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2_del, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3_modify, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4_orders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5_rec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2_ord_min, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1280, 51);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FOOD NAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUANTITY");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TOTAL PRICE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ROLL NO");

        jTextField1_food_name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField1_food_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_food_nameActionPerformed(evt);
            }
        });

        jTextField2_quan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField2_quan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_quanActionPerformed(evt);
            }
        });

        jTextField3_totalpri.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField3_totalpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_totalpriActionPerformed(evt);
            }
        });

        jButton6_done.setBackground(new java.awt.Color(0, 84, 140));
        jButton6_done.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6_done.setForeground(new java.awt.Color(255, 255, 255));
        jButton6_done.setText("DONE");
        jButton6_done.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6_done.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6_doneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6_doneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6_doneMouseExited(evt);
            }
        });

        jLabel5_back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5_back.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5_back.setText("<<back");
        jLabel5_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5_backMouseExited(evt);
            }
        });

        jButton7_cancel.setBackground(new java.awt.Color(0, 84, 140));
        jButton7_cancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7_cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton7_cancel.setText("CANCEL");
        jButton7_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7_cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7_cancelMouseExited(evt);
            }
        });

        jTextField4_rollno.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2_quan, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_food_name, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(jButton6_done, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButton7_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(208, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3_totalpri, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jTextField4_rollno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5_back, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5_back, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_food_name, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2_quan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6_done, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3_totalpri, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(jTextField4_rollno))
                        .addGap(11, 11, 11)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 530, 1280, 270);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FOOD NAME", "QUANTITY", "TOTAL PRICE", "ROLL NO"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 1280, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_addMouseClicked
        // TODO add your handling code here:
         addfood af=new addfood();
        this.setVisible(false);
        af.setVisible(true);
    }//GEN-LAST:event_jButton1_addMouseClicked

    private void jButton1_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_addMouseEntered
        // TODO add your handling code here:
        jButton1_add.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton1_addMouseEntered

    private void jButton1_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_addMouseExited
        // TODO add your handling code here:
        jButton1_add.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton1_addMouseExited

    private void jButton2_delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_delMouseClicked
        // TODO add your handling code here:
         deletefood del=new deletefood();
        this.setVisible(false);
        del.setVisible(true);
    }//GEN-LAST:event_jButton2_delMouseClicked

    private void jButton2_delMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_delMouseEntered
        // TODO add your handling code here:
         jButton2_del.setBackground(new Color(102,102,102));
        
    }//GEN-LAST:event_jButton2_delMouseEntered

    private void jButton2_delMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_delMouseExited
        // TODO add your handling code here:
        jButton2_del.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton2_delMouseExited

    private void jButton3_modifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_modifyMouseClicked
        // TODO add your handling code here:
         modify mod=new modify();
        this.setVisible(false);
        mod.setVisible(true);
        
    }//GEN-LAST:event_jButton3_modifyMouseClicked

    private void jButton3_modifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_modifyMouseEntered
        // TODO add your handling code here:
         jButton3_modify.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton3_modifyMouseEntered

    private void jButton3_modifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_modifyMouseExited
        // TODO add your handling code here:
        jButton3_modify.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton3_modifyMouseExited

    private void jButton4_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_ordersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4_ordersMouseClicked

    private void jButton4_ordersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_ordersMouseEntered
        // TODO add your handling code here:
        jButton4_orders.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton4_ordersMouseEntered

    private void jButton4_ordersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_ordersMouseExited
        // TODO add your handling code here:
        jButton4_orders.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton4_ordersMouseExited

    private void jButton5_recMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5_recMouseClicked
        // TODO add your handling code here:
         record rec=new record();
        this.setVisible(false);
        rec.setVisible(true);
    }//GEN-LAST:event_jButton5_recMouseClicked

    private void jButton5_recMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5_recMouseEntered
        // TODO add your handling code here:
        jButton5_rec.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton5_recMouseEntered

    private void jButton5_recMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5_recMouseExited
        // TODO add your handling code here:
        jButton5_rec.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton5_recMouseExited

    private void jLabel2_ord_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_ord_minMouseClicked
        // TODO add your handling code here:
         this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2_ord_minMouseClicked

    private void jLabel2_ord_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_ord_minMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white);
        jLabel2_ord_min.setBorder(label_border);
        jLabel2_ord_min.setForeground(Color.white);
    }//GEN-LAST:event_jLabel2_ord_minMouseEntered

    private void jLabel2_ord_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_ord_minMouseExited
        // TODO add your handling code here:
         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black);
        jLabel2_ord_min.setBorder(label_border);
        jLabel2_ord_min.setForeground(Color.black);
    }//GEN-LAST:event_jLabel2_ord_minMouseExited

    private void jLabel2_ord_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_ord_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2_ord_closeMouseClicked

    private void jLabel2_ord_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_ord_closeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white);
        jLabel2_ord_close.setBorder(label_border);
        jLabel2_ord_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel2_ord_closeMouseEntered

    private void jLabel2_ord_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2_ord_closeMouseExited
        // TODO add your handling code here:
         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black);
        jLabel2_ord_close.setBorder(label_border);
        jLabel2_ord_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel2_ord_closeMouseExited

    private void jTextField1_food_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_food_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_food_nameActionPerformed

    private void jTextField2_quanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_quanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_quanActionPerformed

    private void jTextField3_totalpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_totalpriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_totalpriActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int rIndex=jTable1.getSelectedRow();
         jTextField1_food_name.setText(model.getValueAt(rIndex, 0).toString());
        jTextField2_quan.setText(model.getValueAt(rIndex, 1).toString());
        jTextField3_totalpri.setText(model.getValueAt(rIndex, 2).toString());
        jTextField4_rollno.setText(model.getValueAt(rIndex, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6_doneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6_doneMouseClicked
        // TODO add your handling code here:
        PreparedStatement ps;
         ResultSet rs;
         String ToEmail;
         String rno=usr.getTab();
         My_CNX mycon=new My_CNX();
         
         String query="SELECT email FROM login WHERE `roll_no`=?";
        try {
              ps= mycon.getConnection().prepareStatement(query);
            ps.setString(1, rno);
            rs=ps.executeQuery();
            while(rs.next()){
           ToEmail = rs.getString(1);
              
             try{
                 Email email=new Email("canteen089@gmail.com","Canteen245");
                 email.setFrom("canteen089@gmail.com","Canteen project");
                 email.setSubject("ABOUT YOUR ORDER");
                 email.setContent("<h3>YOUR ORDER IS READY!!!</h3>","text/html");
                 email.addRecipient(ToEmail);
                 email.send();
             }catch(Exception e){
                 e.printStackTrace();
             }
            
              
              
              
             
              
              
              
            }
        } catch (SQLException ex) {
            Logger.getLogger(orders.class.getName()).log(Level.SEVERE, null, ex);
        }
         String foodName=jTextField1_food_name.getText();
        String quantity=jTextField2_quan.getText();
        String price=jTextField3_totalpri.getText();
        String rollno=jTextField4_rollno.getText();
        usr.Record(rollno,foodName,price,quantity);
        usr.delete(rollno,foodName);
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"FOOD NAME","QUANTITY","TOTAL PRICE","ROLL NO"}));
         usr.fillorderTable(jTable1);
         
        
        
    }//GEN-LAST:event_jButton6_doneMouseClicked

    private void jLabel5_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5_backMouseClicked
        // TODO add your handling code here:
         admin ad=new admin();
        this.setVisible(false);
        ad.setVisible(true);
    }//GEN-LAST:event_jLabel5_backMouseClicked

    private void jLabel5_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5_backMouseEntered
        // TODO add your handling code here:
         jLabel5_back.setForeground(Color.white);
    }//GEN-LAST:event_jLabel5_backMouseEntered

    private void jLabel5_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5_backMouseExited
        // TODO add your handling code here:
         jLabel5_back.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jLabel5_backMouseExited

    private void jButton6_doneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6_doneMouseEntered
        // TODO add your handling code here:
          jButton6_done.setBackground(new Color(0,101,183));
    }//GEN-LAST:event_jButton6_doneMouseEntered

    private void jButton7_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7_cancelMouseEntered
        // TODO add your handling code here:
          jButton7_cancel.setBackground(new Color(0,101,183));
    }//GEN-LAST:event_jButton7_cancelMouseEntered

    private void jButton6_doneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6_doneMouseExited
        // TODO add your handling code here:
         jButton6_done.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_jButton6_doneMouseExited

    private void jButton7_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7_cancelMouseExited
        // TODO add your handling code here:
        jButton7_cancel.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_jButton7_cancelMouseExited

    private void jButton7_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7_cancelMouseClicked
        // TODO add your handling code here:
         jTextField1_food_name.setText("");
        jTextField2_quan.setText("");
        jTextField3_totalpri.setText("");
        jTextField4_rollno.setText("");
    }//GEN-LAST:event_jButton7_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_add;
    private javax.swing.JButton jButton2_del;
    private javax.swing.JButton jButton3_modify;
    private javax.swing.JButton jButton4_orders;
    private javax.swing.JButton jButton5_rec;
    private javax.swing.JButton jButton6_done;
    private javax.swing.JButton jButton7_cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_ord_close;
    private javax.swing.JLabel jLabel2_ord_min;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5_back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_food_name;
    private javax.swing.JTextField jTextField2_quan;
    private javax.swing.JTextField jTextField3_totalpri;
    private javax.swing.JTextField jTextField4_rollno;
    // End of variables declaration//GEN-END:variables

