/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canteen_java;

import java.awt.Color;
import java.util.logging.Level;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;

/**
 *
 * @author abc
 */
public class record extends javax.swing.JFrame {

    private static void log(Level SEVERE, Object object, UnsupportedLookAndFeelException ex) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form record
     */
     USERF usr=new USERF();
    public record() {
        initComponents();
        
         this.setLocationRelativeTo(null);
        usr.fillrecordTable(jTable1);
        
         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black);
        jLabel1.setBorder(label_border);
        jLabel2.setBorder(label_border);
        
          Border glob_panel_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black);
        jPanel1.setBorder(glob_panel_border);
        jPanel2.setBorder(glob_panel_border);
        
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1_add_food = new javax.swing.JButton();
        jButton2_delete_food = new javax.swing.JButton();
        jButton3_modify = new javax.swing.JButton();
        jButton4_orders = new javax.swing.JButton();
        jButton5_records = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 150, 136));

        jButton1_add_food.setBackground(new java.awt.Color(51, 51, 51));
        jButton1_add_food.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_add_food.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_add_food.setText("ADD FOOD");
        jButton1_add_food.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_add_food.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_add_foodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1_add_foodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1_add_foodMouseExited(evt);
            }
        });

        jButton2_delete_food.setBackground(new java.awt.Color(51, 51, 51));
        jButton2_delete_food.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2_delete_food.setForeground(new java.awt.Color(255, 255, 255));
        jButton2_delete_food.setText("DELETE FOOD");
        jButton2_delete_food.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2_delete_food.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_delete_foodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2_delete_foodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2_delete_foodMouseExited(evt);
            }
        });

        jButton3_modify.setBackground(new java.awt.Color(51, 51, 51));
        jButton3_modify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3_modify.setForeground(new java.awt.Color(255, 255, 255));
        jButton3_modify.setText("MODIFY");
        jButton3_modify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3_modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3_modifyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3_modifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3_modifyMouseExited(evt);
            }
        });
        jButton3_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_modifyActionPerformed(evt);
            }
        });

        jButton4_orders.setBackground(new java.awt.Color(51, 51, 51));
        jButton4_orders.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4_orders.setForeground(new java.awt.Color(255, 255, 255));
        jButton4_orders.setText("ORDERS");
        jButton4_orders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4_ordersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4_ordersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4_ordersMouseExited(evt);
            }
        });

        jButton5_records.setBackground(new java.awt.Color(51, 51, 51));
        jButton5_records.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5_records.setForeground(new java.awt.Color(255, 255, 255));
        jButton5_records.setText("RECORDS");
        jButton5_records.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5_records.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5_recordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5_recordsMouseExited(evt);
            }
        });
        jButton5_records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_recordsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("x");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1_add_food, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2_delete_food, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5_records, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1_add_food, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2_delete_food, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5_records, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1280, 50);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ROLL NO", "FOOD NAME", "QUANTITY", "TOTAL PRICE"
            }
        ){public boolean isCellEditable(int row, int column){return false;}});
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 1280, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_modifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3_modifyActionPerformed

    private void jButton5_recordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_recordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5_recordsActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white);
        jLabel1.setBorder(label_border);
        jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black);
        jLabel1.setBorder(label_border);
        jLabel1.setForeground(Color.black);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white);
        jLabel2.setBorder(label_border);
        jLabel2.setForeground(Color.white);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
         Border label_border = BorderFactory.createMatteBorder(1,1,1,1,Color.black);
        jLabel2.setBorder(label_border);
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jButton1_add_foodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_add_foodMouseEntered
        // TODO add your handling code here:
         jButton1_add_food.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton1_add_foodMouseEntered

    private void jButton1_add_foodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_add_foodMouseExited
        // TODO add your handling code here:
         jButton1_add_food.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton1_add_foodMouseExited

    private void jButton2_delete_foodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_delete_foodMouseEntered
        // TODO add your handling code here:
         jButton2_delete_food.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton2_delete_foodMouseEntered

    private void jButton2_delete_foodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_delete_foodMouseExited
        // TODO add your handling code here:
         jButton2_delete_food.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton2_delete_foodMouseExited

    private void jButton3_modifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_modifyMouseEntered
        // TODO add your handling code here:
         jButton3_modify.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton3_modifyMouseEntered

    private void jButton3_modifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_modifyMouseExited
        // TODO add your handling code here:
         jButton3_modify.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton3_modifyMouseExited

    private void jButton4_ordersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_ordersMouseEntered
        // TODO add your handling code here:
         jButton4_orders.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton4_ordersMouseEntered

    private void jButton4_ordersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_ordersMouseExited
        // TODO add your handling code here:
         jButton4_orders.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton4_ordersMouseExited

    private void jButton5_recordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5_recordsMouseEntered
        // TODO add your handling code here:
         jButton5_records.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jButton5_recordsMouseEntered

    private void jButton5_recordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5_recordsMouseExited
        // TODO add your handling code here:
         jButton5_records.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton5_recordsMouseExited

    private void jButton1_add_foodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_add_foodMouseClicked
        // TODO add your handling code here:
        addfood af=new addfood();
        this.setVisible(false);
        af.setVisible(true);
    }//GEN-LAST:event_jButton1_add_foodMouseClicked

    private void jButton2_delete_foodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_delete_foodMouseClicked
        // TODO add your handling code here:
        deletefood del=new deletefood();
        this.setVisible(false);
        del.setVisible(true);
    }//GEN-LAST:event_jButton2_delete_foodMouseClicked

    private void jButton3_modifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_modifyMouseClicked
        // TODO add your handling code here:
         modify mod=new modify();
        this.setVisible(false);
        mod.setVisible(true);
    }//GEN-LAST:event_jButton3_modifyMouseClicked

    private void jButton4_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4_ordersMouseClicked
        // TODO add your handling code here:
         orders ord=new orders();
        this.setVisible(false);
        ord.setVisible(true);
    }//GEN-LAST:event_jButton4_ordersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           
        
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new record().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_add_food;
    private javax.swing.JButton jButton2_delete_food;
    private javax.swing.JButton jButton3_modify;
    private javax.swing.JButton jButton4_orders;
    private javax.swing.JButton jButton5_records;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
